apiVersion: v1
kind: Secret
metadata:
  name: webhook-engine-secrets
  namespace: default
type: Opaque
stringData:
  APP_KEY: "base64:DT3OzRzaBxTAbbFwCM+ZPjBry6gCGhnIaW9udIV9WlE="
  DB_USERNAME: "webhook_user"
  DB_PASSWORD: "webhook_secret_prod_password"
  STRIPE_WEBHOOK_SECRET: "whsec_prod_stripe_secret_12345"
  SHOPIFY_WEBHOOK_SECRET: "shpsec_prod_shopify_secret_67890"
